# Generated by Django 4.1.7 on 2023-02-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.FloatField(default=0, help_text='In minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='null', max_length=350),
            preserve_default=False,
        ),
    ]
